### ISSUE TITLE
Add x86 support

### ISSUE THREAD

**Issue by partipan-dot** [Project-ARTist/module-sdk-gen#3]

**Comment by schrnz** [comment]
I started working on this today. Compiling ARTist for x86 worked out of the box and I have a prototype of an improved SDK that allows to build arm *and* x86 modules. The `logtimization` module works but `trace` is segfaulting. I will post updates here.

**Comment by schrnz** [comment]
We have a first version with multi-arch support that fetches & compiles arm and x86. The segfault was not a problem of the SDK itself
