### ISSUE TITLE
Building Description

### ISSUE THREAD

**Issue by alexcekay** [Project-ARTist/module-sdk-gen#8]
When trying to build a Debian Package using `make deb` it wasn't working as i had to call `make fetch` first. I guess the description in the README or the Makefile should be updated.

Also when building the deb file i get the error: 
"mv: das Verschieben von 'debian/artist-sdk_0.0.1-1_amd64.deb' nach 'releases/' ist nicht möglich: Ist kein Verzeichnis" as the script didn't create the release folder

**Comment by schrnz** [comment]
Hi, thanks you for reporting those issues. I agree in both cases, the requirement to use fetch on a fully-prepared AOSP tree *should* be reflected in the README and all folders should be created automatically for any of the build targets. Please feel free to create corresponding pull requests if you have the time =)
